#spring.application.name=lab-report-service
#server.port=8083
#
## Local Testing Bypasses
#spring.config.import=optional:configserver:http://localhost:8888
#eureka.client.enabled=false
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false
#
## GCP Storage Bucket Configuration
#gcp.bucket.name=medportal-lab-reports-bucket

spring.application.name=appointment-service
spring.config.import=optional:configserver:http://localhost:8888